SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `ZERTIFIKATE`
-- ----------------------------
-- DROP TABLE IF EXISTS `ZERTIFIKATE`;
CREATE TABLE `ZERTIFIKATE` (
  `ID` int(4) unsigned NOT NULL AUTO_INCREMENT,
  `CERTCENTER_ORDERID` int(4) unsigned NOT NULL DEFAULT '0',
  `TS_INSERT` int(4) unsigned NOT NULL DEFAULT '0',
  `TS_UPDATE` int(4) unsigned NOT NULL DEFAULT '0',
  `STATUS` enum('PENDING','CANCELLED','COMPLETE','REVOKED') NOT NULL DEFAULT 'PENDING',
  `START_DATE` int(4) unsigned NOT NULL DEFAULT '0',
  `END_DATE` int(4) unsigned NOT NULL DEFAULT '0',
  `KUNDE_NR` varchar(20) DEFAULT NULL,
  `EMAIL_RECIPIENT` varchar(255) DEFAULT NULL,
  `PRODUCT_CODE` varchar(30) NOT NULL,
  `VALIDITY_PERIOD` int(4) NOT NULL,
  `RENEW` bit(1) NOT NULL,
  `CUPGRADE` bit(1) NOT NULL,
  `LICENSES` tinyint(3) NOT NULL,
  `PLATFORM` varchar(30) NOT NULL,
  `SAN_HOSTS` tinytext,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `TS_INSERT` (`TS_INSERT`),
  KEY `CERTCENTER_ORDERID` (`CERTCENTER_ORDERID`),
  KEY `STATUS` (`STATUS`),
  KEY `START_DATE` (`START_DATE`),
  KEY `END_DATE` (`END_DATE`)
) DEFAULT CHARSET=utf8;
delimiter ;;
CREATE TRIGGER `ZERTIFIKATE_ON_BEFORE_INSERT` BEFORE INSERT ON `ZERTIFIKATE` FOR EACH ROW BEGIN
	SET NEW.TS_INSERT = UNIX_TIMESTAMP();
	SET NEW.TS_UPDATE = NEW.TS_INSERT;
END;
 ;;
delimiter ;
delimiter ;;
CREATE TRIGGER `ZERTIFIKATE_ON_BEFORE_UPDATE` BEFORE UPDATE ON `ZERTIFIKATE` FOR EACH ROW BEGIN
	SET NEW.TS_UPDATE = UNIX_TIMESTAMP();
END;
 ;;
delimiter ;

